site_name: Notes
nav:
  - Home: index.md
theme:
  name: material
markdown_extensions:
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true